name: gobuild-upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: sync cnb
        run: |
          git fetch --unshallow
          TOKEN=${{ secrets.CNB_TOKEN }} TO_GIT=cnb TAG=${GITHUB_REF_NAME}  bash sync.sh

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.9'

      - name: Run Go Multi-Platform Build Action
        id: build
        uses: chihqiang/gobuild-action@main
        with:
          main_go: cmd/tlsctl/main.go
          bin_name: tlsctl
          add_files: |
            README.md
            LICENSE

      - name: Upload release assets
        uses: chihqiang/upload-asset-action@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          files: ${{ env.GOBUILD_FILES }}